<?php

/**
 * @file
 * Represents hook definitions and common functions.
 */

require_once 'ding_event_subscriptions.pages.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_event_subscriptions_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_menu().
 */
function ding_event_subscriptions_menu() {
  $items = array();

  $items['ding-event-subscriptions/download-ics'] = array(
    'page callback' => 'ding_event_subscriptions_callback',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ding_event_subscriptions_theme($existing, $type, $theme, $path) {
  return array(
    'ding_event_subscriptions_ics' => array(
      'variables' => array('events' => NULL),
    ),
  );
}

/**
 * Helper function for generating url with params depending on current path.
 *
 * @return bool|string
 *   Generated url or FALSE on failing.
 */
function ding_event_subscriptions_generate_url() {
  $menu = menu_get_item();
  if (!empty($menu)) {
    $maps = $menu['map'];
    $conditions = array();
    switch ($maps[0]) {
      case 'node':
        $node = $maps[1];
        switch ($node->type) {
          case 'ding_library':
            $conditions['library'] = $node->nid;
            break;

          case 'ding_event':
            $conditions['event'] = $node->nid;
            break;
        }
        break;

      case 'bibliotek':
        $context = $maps[1];
        $conditions['library'] = $context->argument;
        if (!empty($maps[3])) {
          $conditions['category'] = $maps[3];
        }
        break;

      case 'taxonomy':
        $term = $maps[2];
        $conditions['category'] = $term->tid;
        break;
    }

    $url = url('ding-event-subscriptions/download-ics', array(
      'query' => $conditions,
    ));

    $os = ding_event_subscriptions_get_os();
    if (!empty($os) && in_array($os, array('Mac', 'iOS')) && !isset($conditions['event'])) {
      $url = 'webcal://' . $_SERVER['SERVER_NAME'] . '/ding-event-subscriptions/download-ics';
      if (!empty($conditions)) {
        array_walk($conditions, function (&$i, $k) {
          $i = "{$k}={$i}";
        });

        $conditions = implode('&', $conditions);
        $url .= '?' . $conditions;
      }
    }
    return $url;
  }
  return FALSE;
}

/**
 * Helper function for getting events by conditions.
 *
 * @param array $conditions
 *   Array with conditions for getting events.
 *
 * @return array
 *   Array of event nodes.
 */
function ding_event_subscriptions_get_events(array $conditions = array()) {
  $events = array();
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'ding_event')
    ->propertyCondition('status', NODE_PUBLISHED);

  if (!empty($conditions['event'])) {
    $query->propertyCondition('nid', $conditions['event']);
  }

  if (!empty($conditions['category'])) {
    $query->fieldCondition('field_ding_event_category', 'tid', $conditions['category'], '=');
  }

  if (!empty($conditions['library'])) {
    $query->fieldCondition('og_group_ref', 'target_id ', $conditions['library'], '=');
  }

  $query->addTag('ding_event_subscriptions');

  $result = $query->execute();
  if (isset($result['node'])) {
    foreach ($result['node'] as $data) {
      $events[$data->nid] = node_load($data->nid);
    }
  }

  return $events;
}

/**
 * Theme function for generating ics file based on list of events.
 *
 * @param array $variables
 *   Array with accessible variables.
 *
 * @return string
 *   Generated list of events in ICS format.
 */
function theme_ding_event_subscriptions_ics(&$variables) {
  $output = '';
  $events = $variables['events'];
  $output .= ding_event_subscriptions_line('BEGIN', 'VCALENDAR', FALSE);
  $output .= ding_event_subscriptions_line('PRODID', '-//EasySuite//DK', FALSE);
  $output .= ding_event_subscriptions_line('VERSION', '2.0', FALSE);
  $output .= ding_event_subscriptions_line('METHOD', 'PUBLISH', FALSE);
  $output .= ding_event_subscriptions_line('X-MS-OLK-FORCEINSPECTOROPEN', 'TRUE', FALSE);
  if (count($events) != 1) {
    $output .= ding_event_subscriptions_line('X-WR-CALNAME', t('Library calendar'), FALSE);
  }
  $output .= ding_event_subscriptions_line('CALSCALE', 'GREGORIAN', FALSE);
  foreach ($events as $event) {
    // Preparing note content for event.
    $body = field_get_items('node', $event, 'field_ding_event_body');
    if (isset($body[0])) {
      $body = field_view_value('node', $event, 'field_ding_event_body', $body[0]);
      $body = trim(render($body));
    }
    else {
      $body = '';
    }

    $teaser = field_get_items('node', $event, 'field_ding_event_lead');
    if (isset($teaser[0])) {
      $teaser = field_view_value('node', $event, 'field_ding_event_lead', $teaser[0]);
      $teaser = trim(render($teaser));
    }
    else {
      $teaser = '';
    }

    $url = url("node/{$event->nid}", array(
      'absolute' => TRUE,
    ));

    $teaser = preg_replace("/\r|\n/", "", $teaser);
    $body = preg_replace("/\r|\n/", "", drupal_html_to_text($body));

    // Price processing.
    $unformatted_price = field_get_items('node', $event, 'field_ding_event_price');
    $unformatted_price = !empty($unformatted_price[0]['value']) ? $unformatted_price[0]['value'] : '';
    if (!empty($unformatted_price)) {
      $price = t('Price: @unformatted_price Kr', array('@unformatted_price' => $unformatted_price));
    }
    else {
      $price = t('Free');
    }

    $full_description = '';
    $full_description .= $url . "\\n\\n";
    $full_description .= $price . "\\n\\n";
    $full_description .= $teaser . "\\n\\n";
    $full_description .= $body;

    // Dates processing.
    $date = field_get_items('node', $event, 'field_ding_event_date');
    $timezone_db = new DateTimeZone($date[0]['timezone_db']);
    $timezone = new DateTimeZone($date[0]['timezone']);
    $start = new DateTime($date[0]['value'], $timezone_db);
    $start->setTimezone($timezone);
    $end = new DateTime($date[0]['value2'], $timezone_db);
    $end->setTimezone($timezone);
    $now = new DateTime(date('Y-m-d H:i:s'), $timezone_db);
    $now->setTimezone($timezone);

    // Location processing.
    $event_location = field_get_items('node', $event, 'field_ding_event_location');

    if (empty($event_location[0]['name_line'])) {
      $lib_ref = field_get_items('node', $event, 'og_group_ref');
      if (!empty($lib_ref)) {
        $library = node_load($lib_ref[0]['target_id']);

        $lib_contacts = field_get_items('node', $library, 'field_ding_library_addresse');

        $location = array(
          'name_line' => $library->title,
          'thoroughfare' => $lib_contacts[0]['thoroughfare'],
          'premise' => $lib_contacts[0]['premise'],
          'postal_code_locality' => $lib_contacts[0]['postal_code'] . ' ' . $lib_contacts[0]['locality'],
        );
      }
    }
    else {
      $location = array(
        'name_line' => $event_location[0]['name_line'],
        'thoroughfare' => $event_location[0]['thoroughfare'],
        'premise' => $event_location[0]['premise'],
        'postal_code_locality' => $event_location[0]['postal_code'] . ' ' . $event_location[0]['locality'],
      );
    }

    $location = implode('; ', $location);

    // UID processing.
    $uid = uniqid();

    // Preparing CREATED tag content.
    $created = new DateTime();
    $created->setTimestamp($event->created);
    $created = $created->format('Ymd\THis');

    // Preparing LAST-MODIFIED tag content.
    $updated = new DateTime();
    $updated->setTimestamp($event->changed);
    $updated = $updated->format('Ymd\THis');

    $output .= ding_event_subscriptions_line('BEGIN', 'VEVENT', FALSE);
    $output .= ding_event_subscriptions_line('CREATED', $created, FALSE);
    $output .= ding_event_subscriptions_line('LAST-MODIFIED', $updated, FALSE);
    $output .= ding_event_subscriptions_line('CLASS', 'PUBLIC', FALSE);
    $output .= ding_event_subscriptions_line('UID', $uid, FALSE);
    $output .= ding_event_subscriptions_line('SUMMARY', $event->title);
    $output .= ding_event_subscriptions_line('DESCRIPTION', $full_description, TRUE);
    $output .= ding_event_subscriptions_line('URL', $url, FALSE);
    $output .= ding_event_subscriptions_line('PRICE', $price);
    $output .= ding_event_subscriptions_line('DTSTART', $start->format('Ymd\THis'), FALSE);
    $output .= ding_event_subscriptions_line('DTEND', $end->format('Ymd\THis'), FALSE);
    $output .= ding_event_subscriptions_line('DTSTAMP', $now->format('Ymd\THis'), FALSE);
    $output .= ding_event_subscriptions_line('LOCATION', $location);
    $output .= ding_event_subscriptions_line('X-MICROSOFT-CDO-BUSYSTATUS', 'BUSY');
    $output .= ding_event_subscriptions_line('X-MICROSOFT-CDO-IMPORTANCE', '1');
    $output .= ding_event_subscriptions_line('X-MICROSOFT-DISALLOW-COUNTER', 'FALSE');
    $output .= ding_event_subscriptions_line('X-MS-OLK-ALLOWEXTERNCHECK', 'TRUE');
    $output .= ding_event_subscriptions_line('X-MS-OLK-AUTOFILLLOCATION', 'FALSE');
    $output .= ding_event_subscriptions_line('X-MS-OLK-CONFTYPE', '0');
    $output .= ding_event_subscriptions_line('TRANSP', 'OPAQUE');
    $output .= ding_event_subscriptions_line('PRIORITY', '5');
    $output .= ding_event_subscriptions_line('SEQUENCE', '0');
    $output .= ding_event_subscriptions_line('END', 'VEVENT');
  }
  $output .= ding_event_subscriptions_line('END', 'VCALENDAR');

  return $output;
}

/**
 * Helper function for generating line of ICF file.
 *
 * @param string $name
 *   Name of param.
 * @param string $value
 *   Value of param.
 * @param bool $escape
 *   Indicates should value be escaped or not.
 *
 * @return string
 *   Formatted line of file.
 */
function ding_event_subscriptions_line($name, $value, $escape = TRUE) {
  $name = drupal_strtoupper($name);
  if ($escape) {
    $value = ding_event_subscriptions_escape($value);
  }
  return "{$name}:{$value}\r\n";
}

/**
 * Helper function for escaping values of ICS file.
 *
 * @param string $data
 *   Represent data which should be escaped.
 *
 * @return mixed
 *   Escaped string or false.
 */
function ding_event_subscriptions_escape($data) {
  return preg_replace('/([\,;]\s)/', '\\\$1', $data);
}

/**
 * Implements hook_query_TAG_alter().
 */
function ding_event_subscriptions_query_ding_event_subscriptions_alter(QueryAlterableInterface $query) {
  $query->leftJoin('field_data_field_ding_event_date', 'f', 'node.nid = f.entity_id');
  $query->where(':time <= f.field_ding_event_date_value2', array(':time' => date('Y-m-d H:i:s')));
}

/**
 * Implements hook_field_extra_fields().
 */
function ding_event_subscriptions_field_extra_fields() {
  $extra = array();

  $extra['node']['ding_event']['display'] = array(
    'field_ding_event_subscriptions' => array(
      'label' => t('Subscribe'),
      'description' => t('Represents subscribe link.'),
      'weight' => 99,
      // It is required for integration with extrafield_views_integration.
      'callback' => 'ding_event_subscriptions_extra_callback',
    ),
  );

  return $extra;
}

/**
 * Helper function for getting markup of extra field.
 */
function ding_event_subscriptions_extra_callback($entity) {
  global $base_url;
  $path = drupal_get_path('module', 'ding_event_subscriptions');
  $os = ding_event_subscriptions_get_os();
  $reference = ding_event_subscriptions_generate_url();
  $output = array(
    '#markup' => l(t('Add event to calendar'), '#', array(
      'attributes' => array(
        'class' => array('ding-event-subscriptions'),
        'data-reference' => $reference,
        'data-domain' => $base_url,
      ),
    )),
    '#attached' => array(
      'js' => array($path . '/js/ding_event_subscriptions.js'),
      'css' => array($path . '/css/ding_event_subscriptions.css'),
    ),
  );
  return $output;
}

/**
 * Implements hook_entity_view().
 */
function ding_event_subscriptions_entity_view($entity, $type, $view_mode, $langcode) {
  if (isset($entity->type)) {
    $extra_fields = field_info_extra_fields($type, $entity->type, 'display');
    if (isset($extra_fields['field_ding_event_subscriptions'])) {
      $entity->content['field_ding_event_subscriptions'] = ding_event_subscriptions_extra_callback($entity);
    }
  }
}

/**
 * Helper function for getting operation system.
 *
 * @return mixed|string
 *   Detected system of NULL.
 */
function ding_event_subscriptions_get_os() {
  $user_agent = $_SERVER['HTTP_USER_AGENT'];
  $os_platform = NULL;

  $os_array = array(
    '/windows nt \d{1,2}\.\d/i' => 'Windows',
    '/windows \w{2}/i' => 'Windows',
    '/win\d{2}/i' => 'Windows 98',
    '/macintosh|mac os x|mac_powerpc/i' => 'Mac',
    '/linux/i' => 'Linux',
    '/ubuntu/i' => 'Ubuntu',
    '/iphone/i' => 'iOS',
    '/ipod/i' => 'iOS',
    '/ipad/i' => 'iOS',
    '/android/i' => 'Android',
    '/blackberry/i' => 'BlackBerry',
    '/webos/i' => 'Mobile',
  );

  foreach ($os_array as $regex => $value) {
    if (preg_match($regex, $user_agent)) {
      $os_platform = $value;
    }
  }

  return $os_platform;
}
